{ config, pkgs, inputs, ... }:

{
  imports = [ ./hardware-configuration.nix ]; # Generated by the installer

# --- BOOTLOADER: GRUB ---
  # We disable systemd-boot and enable GRUB with OS Prober
  boot.loader.systemd-boot.enable = false;
  
  boot.loader.grub = {
    enable = true;
    device = "nodev";      # "nodev" is correct for EFI
    efiSupport = true;
    useOSProber = true;    # This finds Windows and Arch automatically
    
    # Allow GRUB to modify EFI variables
    efiInstallAsRemovable = false; 
  };
  boot.loader.efi.canTouchEfiVariables = true;

  # --- MOUNTING ARCH LINUX ---
  # 1. Unlock LUKS container at boot
  boot.initrd.luks.devices."cryptdev" = {
    device = "/dev/disk/by-uuid/d3719f15-99c8-4217-8b8e-6c0384732c4e"; # UUID of nvme0n1p6
    # If you want to unlock it automatically with a keyfile later, 
    # you add the keyfile config here. For now, it will ask for password.
  };

  # 2. Mount Arch Home partition
  fileSystems."/home/ved/arch_home" = {
    device = "/dev/mapper/cryptdev"; 
    fsType = "btrfs";
    options = [ "subvol=@home" ]; # REPLACE '@home' with your actual subvol name
  };


  # Netowrking
  networking.hostName = "thinkpad"; 
  networking.networkmanager.enable = true; # nm-cli applet needs this

  # Time & Locale
  time.timeZone = "America/Los_Angeles";
  i18n.defaultLocale = "en_US.UTF_8";

  # User Account
  users.users.ved = {
    isNormalUser = true;
    description = "Ved Shastry";
    extraGroups = [ "networkmanager" "wheel" "docker" "video" "audio" ];
    shell = pkgs.zsh;
  };

  # Graphics & Hardware
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };
  services.fprintd.enable = true; # Fingerprint reader

  # Cloudflare WARP (Systemd Service)
  systemd.packages = [ pkgs.cloudflare-warp ]; 
  systemd.services.warp-svc.wantedBy = [ "multi-user.target" ];

  # Allow Unfree Software (Dropbox, WARP, Stata deps)
  nixpkgs.config.allowUnfree = true;

  # System Packages (The "Base" layer)
  environment.systemPackages = with pkgs; [

    # Suckless dependencies
    xorg.libX11 xorg.libXft xorg.libXinerama

    # Suckless Basics (Standard versions for now)
      st
      dmenu
      slstatus 

      # Workflow
      pulsar       # Editor
      firefox      # Backup browser
      git
      wget
      vim
      neovim
      ranger
      ripgrep
      fd
      cloudflare-warp
      
      # Cloud
      dropbox
      
      # System Management
      pavucontrol  # Audio GUI
      htop

  ];

  # The "Suckless" Build Strategy
  # We overlay your local source code on top of the default dwm package
  nixpkgs.overlays = [
    (final: prev: {
      dwm = prev.dwm.overrideAttrs (old: {
        src = /home/ved/arch_home/repos/dwm;
      });
      st = prev.st.overrideAttrs (old: {
        src = /home/ved/arch_home/repos/dmenu;
      });
      st = prev.st.overrideAttrs (old: {
        src = /home/ved/arch_home/repos/st;
      });
      slstatus = prev.slstatus.overrideAttrs (old: {
        src = /home/ved/arch_home/repos/slstatus;
      });
    })
  ];

  services.xserver = {
    enable = true;
    windowManager.dwm.enable = true;
    displayManager.startx.enable = true; # Keep it simple, or use a DM like sddm
  };
  
  # Fonts
  fonts.packages = with pkgs; [
    font-awesome
    nerd-fonts.jetbrains-mono
    nerd-fonts.symbols-only
  ];

  # Essential Hardware Tweaks (ThinkPad T14 Gen 5)
  boot.kernelPackages = pkgs.linuxPackages_latest; # 6.12+ kernel for HawkPoint APU
  services.fwupd.enable = true; # Firmware updates

  system.stateVersion = "24.11";
}
