{ config, pkgs, inputs, ... }:

{
  imports = [ ./hardware-configuration.nix ]; # Generated by the installer

# --- BOOTLOADER: GRUB ---
  boot.loader.systemd-boot.enable = false; # Disable systemd-boot
  boot.loader.grub = {     # GRUB options
    enable = true;
    device = "nodev";      # "nodev" is correct for EFI
    efiSupport = true;
    enableCryptodisk = true; # mount encrypted partitions
    useOSProber = true;    # run os-prober
    efiInstallAsRemovable = false; # Allow GRUB to modify EFI variables

    # GRUB cmdline entries
    extraEntries = ''
        menuentry "Arch Linux" {
        insmod luks
        insmod btrfs
        cryptomount -u d3719f1599c842178b8e6c0384732c4e
        set root='(crypto0)'
        linux /@/boot/vmlinuz-linux-zen rw rootflags=subvol=@ cryptdevice=UUID=d3719f15-99c8-4217-8b8e-6c0384732c4e:cryptdev root=/dev/mapper/cryptdev quiet
        initrd /@/boot/amd-ucode.img /@/boot/initramfs-linux-zen.img
        }
    '';
  };
  boot.loader.efi.canTouchEfiVariables = true; # EFI vars
  # NixOS initrd unlocks the cryptdrive so it can mount arch_home/ved
  boot.initrd.luks.devices."cryptdev".device = "/dev/disk/by-uuid/d3719f15-99c8-4217-8b8e-6c0384732c4e";

  # 2. Mount Arch Home partition
  fileSystems."/home/ved/arch_home" = {
    device = "/dev/mapper/cryptdev";
    fsType = "btrfs";
    options = [ "subvol=@home" ]; # subvol name
  };

  # 3. Mount Arch Root partition
  fileSystems."/home/ved/arch_root" = {
    device = "/dev/mapper/cryptdev";
    fsType = "btrfs";
    options = [ "subvol=@" ]; # subvol name
  };

  # Networking
  networking.hostName = "thinkpad";
  networking.networkmanager.enable = true; # nm-cli applet needs this

  # Time & Locale
  time.timeZone = "America/Los_Angeles";
  i18n.defaultLocale = "en_US.UTF-8";
  i18n.extraLocaleSettings = {
    LC_MONETARY = "en_US.UTF-8";
    LC_TELEPHONE = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
  };

  # User Account
  users.users.ved = {
    isNormalUser = true;
    uid = 1000;
    description = "Ved Shastry";
    extraGroups = [ "networkmanager" "wheel" "docker" "video" "audio" ];
    shell = pkgs.zsh;
  };

  # Graphics & Hardware
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };
  services.fprintd.enable = true; # Fingerprint reader
  services.printing.enable = true; # Enable CUPS to print documents.

  # Enable sound with pipewire.
  services.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    # If you want to use JACK applications, uncomment this
    #jack.enable = true;

    # use the example session manager (no others are packaged yet so this is enabled by default,
    # no need to redefine it in your config for now)
    #media-session.enable = true;
  };

  # Cloudflare WARP (Systemd Service)
  systemd.packages = [ pkgs.cloudflare-warp ];
  systemd.services.warp-svc.wantedBy = [ "multi-user.target" ];

  # Allow Unfree Software
  nixpkgs.config.allowUnfree = true;

# Allow Insecure Packages
  nixpkgs.config.permittedInsecurePackages = [
    "pulsar-1.129.0"  # Pulsar editor
  ];

  # System Packages (The "Base" layer)
  environment.systemPackages = with pkgs; [

    # Suckless dependencies
    xorg.libX11 xorg.libXft xorg.libXinerama

    # Suckless Basics (Standard versions for now)
      st
      dmenu
      dwm
      slstatus

      # Workflow
      #pulsar       # Editor
      git
      wget
      vim
      neovim
      ranger
      ripgrep
      fd
      cryptsetup
      zsh

      # System Management
      pavucontrol  # Audio GUI
      htop

  ];

  # enable zsh
  programs.zsh.enable=true;

  # suckless tools
  /*
  nixpkgs.overlays = [
    (final: prev: {
      dwm = prev.dwm.overrideAttrs (old: {
        src = /home/ved/arch_home/ved/repos/dwm;
      });
      dmenu = prev.dmenu.overrideAttrs (old: {
        src = /home/ved/arch_home/ved/repos/dmenu;
      });
      st = prev.st.overrideAttrs (old: {
        src = /home/ved/arch_home/ved/repos/st;
      });
      slstatus = prev.slstatus.overrideAttrs (old: {
        src = /home/ved/arch_home/ved/repos/slstatus;
      });
    })
  ];
  */

  services.xserver = {
    enable = true;
    windowManager.dwm.enable = true;
    displayManager.startx.enable = true; # Keep it simple, or use a DM like sddm
  };
  services.libinput.enable = true; # Enable touchpad support

  # Fonts
  fonts.packages = with pkgs; [
    font-awesome
    nerd-fonts.jetbrains-mono
    nerd-fonts.symbols-only
  ];

  # Essential Hardware Tweaks (ThinkPad T14 Gen 5)
  boot.kernelPackages = pkgs.linuxPackages_latest; # 6.12+ kernel for HawkPoint APU
  services.fwupd.enable = true; # Firmware updates

  # Leave at the release version of first install (25.11)
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "25.11";
}
