# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # ThinkPad T14 Gen 5
  boot.kernelPackages = pkgs.linuxPackages_latest; # Latest linux kernel
  #boot.kernelPackages = pkgs.linuxPackages_zen; # Linux-zen kernel
  services.fwupd.enable = true; # Firmware updates

  # Boot options
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "ntfs" ];
  boot.loader.efi.canTouchEfiVariables = true; # EFI vars

  # GRUB
  boot.loader.systemd-boot.enable = false; # Disable systemd-boot
  boot.loader.grub = {     # GRUB options
    enable = true;
    device = "nodev";      # "nodev" is correct for EFI
    efiSupport = true;
    enableCryptodisk = true; # mount encrypted partitions
    useOSProber = true;    # run os-prober
    efiInstallAsRemovable = false; # Allow GRUB to modify EFI variables
    theme = null;
    splashImage = null;
    backgroundColor = "black";

    extraConfig = ''
    # Normal text: Light gray on black
    set color_normal=light-gray/black

    # Highlighted text: Light blue on black
    set color_highlight=light-blue/black

    # Menu border
    set menu_color_normal=light-gray/black
    set menu_color_highlight=light-blue/black
    '';

    # GRUB cmdline entries
    extraEntries = ''
        menuentry "Arch Linux" {
        insmod luks
        insmod btrfs
        cryptomount -u d3719f1599c842178b8e6c0384732c4e
        set root='(crypto0)'
        linux /@/boot/vmlinuz-linux-zen rw rootflags=subvol=@ cryptdevice=UUID=d3719f15-99c8-4217-8b8e-6c0384732c4e:cryptdev root=/dev/mapper/cryptdev quiet
        initrd /@/boot/amd-ucode.img /@/boot/initramfs-linux-zen.img
        }
    '';
  };

  # NixOS initrd unlocks the encrypted partition to mount
  boot.initrd.luks.devices."cryptdev".device = "/dev/disk/by-uuid/d3719f15-99c8-4217-8b8e-6c0384732c4e";

  # Mount Arch Root partition
  fileSystems."/mnt/arch" = {
    device = "/dev/mapper/cryptdev";
    fsType = "btrfs";
    options = [ "subvol=@" "noatime" "compress=zstd"]; # subvol name
  };

  # Mount Arch Home partition
  fileSystems."/mnt/arch/home" = {
    device = "/dev/mapper/cryptdev";
    fsType = "btrfs";
    options = [ "subvol=@home" "noatime" "compress=zstd"]; # subvol name
  };

	# Mount NTFS
	fileSystems."/mnt/d" = {
	  device = "/dev/disk/by-uuid/26C43682C43653F1";
	  fsType = "ntfs3";
	};


  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ad11104f-f8b7-4bbd-9739-9fcd4ba76581";
      fsType = "btrfs";
      options = [ "subvol=@" "noatime" "compress=zstd" ]; # subvol name
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/ad11104f-f8b7-4bbd-9739-9fcd4ba76581";
      fsType = "btrfs";
      options = [ "subvol=@home" "noatime" "compress=zstd"]; # subvol name
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FD3A-619D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
